package co.edu.unicolombo.pb.proaula.views;

import co.edu.unicolombo.pb.proaula.conceptos.Cliente;
import co.edu.unicolombo.pb.proaula.crud.GestionVentas;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class VentanaRegistro extends javax.swing.JFrame {

    public static GestionVentas gestionVenta;

    public VentanaRegistro() {

        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        int x = (int) ((screenSize.getWidth() - this.getWidth()) / 2);
        int y = (int) ((screenSize.getHeight() - this.getHeight()) / 2);

        this.setLocation(x, y);
        btnSiguiente.setEnabled(false);

        SetImageLabel(etiImagen, "src/imagenes/comida italiana.jpg");
        gestionVenta = new GestionVentas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        bienvenida = new javax.swing.JLabel();
        etiNombre = new javax.swing.JLabel();
        nombreText = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        etiMensaje2 = new javax.swing.JLabel();
        etiImagen = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        etiNombre1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        documentoText1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bambino");
        setResizable(false);

        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bienvenida.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        bienvenida.setForeground(new java.awt.Color(255, 255, 255));
        bienvenida.setText("Registro");
        bienvenida.setAlignmentX(0.5F);
        fondo.add(bienvenida, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 120, -1));

        etiNombre.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        etiNombre.setForeground(new java.awt.Color(255, 255, 255));
        etiNombre.setText("DOCUMENTO");
        fondo.add(etiNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 140, 24));

        nombreText.setBackground(new java.awt.Color(255, 255, 255));
        nombreText.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        nombreText.setForeground(new java.awt.Color(204, 204, 204));
        nombreText.setText("Ingrese su nombre de usuario");
        nombreText.setBorder(null);
        nombreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextActionPerformed(evt);
            }
        });
        fondo.add(nombreText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 370, 30));

        btnSiguiente.setBackground(new java.awt.Color(153, 255, 153));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        fondo.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, -1, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        fondo.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        etiMensaje2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiMensaje2.setForeground(new java.awt.Color(255, 255, 255));
        fondo.add(etiMensaje2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 220, 25));

        etiImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/comida italiana.jpg"))); // NOI18N
        fondo.add(etiImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 280, 500));
        fondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 370, -1));

        etiNombre1.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        etiNombre1.setForeground(new java.awt.Color(255, 255, 255));
        etiNombre1.setText("USUARIO");
        fondo.add(etiNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 140, 24));
        fondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 370, -1));

        documentoText1.setBackground(new java.awt.Color(255, 255, 255));
        documentoText1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        documentoText1.setForeground(new java.awt.Color(204, 204, 204));
        documentoText1.setText("Ingrese su número de documento");
        documentoText1.setBorder(null);
        documentoText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoText1ActionPerformed(evt);
            }
        });
        fondo.add(documentoText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 370, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Cliente cliente = new Cliente();
        cliente.nombre = nombreText.getText();
        cliente.documento = nombreText.getText();
        if (cliente.nombre.isEmpty() || !validarCaracteres(cliente.nombre) || cliente.nombre.charAt(0) == ' ') {
            JOptionPane.showMessageDialog(null, "Nombre invalido.");
            return;
        }

        if (!validarNumeros(cliente.documento) || cliente.documento.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Número de documento invalido.");
            return;
        }

        etiMensaje2.setText("Registro realizado con exito");
        
        gestionVenta.setCliente(cliente);
        
        btnSiguiente.setEnabled(true);
        try {
            BufferedWriter writer = new BufferedWriter(new FileWriter("Datos.txt", true));
            writer.write("DATOS CLIENTE");
            writer.newLine();
            writer.write("\nNombre: " + cliente.nombre + "\nDocumento: " + cliente.documento + "\n");
            writer.write("");
            writer.newLine();

            writer.close();
        } catch (IOException e) {
            System.err.println("Error al escribir en el archivo.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        
        
        VentanaMenu menu = new VentanaMenu();
        //menu.setTitle("SALUDOS " + VentanaPrincipal.gestionVenta.getVenta().cliente.nombre); 
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, "Para seleccionar un plato presione su nombre");
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void nombreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextActionPerformed
        // TODO add your handling code here:
        btnGuardar.doClick();
    }//GEN-LAST:event_nombreTextActionPerformed

    private void documentoText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_documentoText1ActionPerformed

    public void SetImageLabel(JLabel nombrelabel, String root) {
        ImageIcon imagen = new ImageIcon(root);
        Icon icon = new ImageIcon(
                imagen.getImage().getScaledInstance(nombrelabel.getWidth(), nombrelabel.getHeight(), Image.SCALE_DEFAULT));
        nombrelabel.setIcon(icon);
        this.repaint();
    }

    public static boolean validarCaracteres(String datos) {
        return datos.matches("[a-z A-Z]*");
    }

    public static boolean validarNumeros(String datos) {
        return datos.matches("[0-9]*");
    }

// Agrega un ComponentListener a tu JFrame para detectar cambios de tamaño
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bienvenida;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JTextField documentoText1;
    private javax.swing.JLabel etiImagen;
    private javax.swing.JLabel etiMensaje2;
    private javax.swing.JLabel etiNombre;
    private javax.swing.JLabel etiNombre1;
    private javax.swing.JPanel fondo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nombreText;
    // End of variables declaration//GEN-END:variables
}
