
package co.edu.unicolombo.pb.proaula.views;

import co.edu.unicolombo.pb.proaula.conceptos.Producto;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author alvar
 */
public final class VentanaMenu extends javax.swing.JFrame {

    /**
     * Creates new form MenuRestaurante
     */
    
    public VentanaMenu() {
        
        initComponents();
         SetImageLabel(etiPizza,"src/imagenes/pizza.jpeg");
         SetImageLabel(etiImangenBebidas,"src/imagenes/Limonada.jpg");
          SetImageLabel(etiFondo,"src/imagenes/menu2.jpg");
         SetImageLabel(etipasta,"src/imagenes/pastas.jpg");
           
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

            int x = (int) ((screenSize.getWidth() - this.getWidth()) / 2);
            int y = (int) ((screenSize.getHeight() - this.getHeight()) / 2);

            this.setLocation(x, y);
         
        String saludo = "Saludos Sr(a)  " + VentanaPrincipal.gestionVenta.getVenta().cliente.nombre + " Bienvenidos a Bambino";
        etiSaludo.setText(saludo);     
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiPizza = new javax.swing.JLabel();
        pizzaNapolitana = new javax.swing.JLabel();
        precPizzaNapolitana = new javax.swing.JLabel();
        signoPrecio = new javax.swing.JLabel();
        etiImangenBebidas = new javax.swing.JLabel();
        pizzaMargarita = new javax.swing.JLabel();
        precPizzaMargarita = new javax.swing.JLabel();
        signoPrecio1 = new javax.swing.JLabel();
        pizzaCapricciosa = new javax.swing.JLabel();
        precPizzaCapricciosa = new javax.swing.JLabel();
        signoPrecio2 = new javax.swing.JLabel();
        pizzaFruttidimare = new javax.swing.JLabel();
        precPizzaFruttidimare = new javax.swing.JLabel();
        signoPrecio3 = new javax.swing.JLabel();
        pizzaBoscaiola = new javax.swing.JLabel();
        precPizzaBoscaiola = new javax.swing.JLabel();
        signoPrecio4 = new javax.swing.JLabel();
        etiLimonada = new javax.swing.JLabel();
        precioLimonada = new javax.swing.JLabel();
        signoPrecio5 = new javax.swing.JLabel();
        etiCocacola = new javax.swing.JLabel();
        precioCocacola = new javax.swing.JLabel();
        signoPrecio6 = new javax.swing.JLabel();
        etiPepsi = new javax.swing.JLabel();
        precioPepsi = new javax.swing.JLabel();
        signoPrecio7 = new javax.swing.JLabel();
        etiAgua = new javax.swing.JLabel();
        precioAgua = new javax.swing.JLabel();
        signoPrecio8 = new javax.swing.JLabel();
        etiAguamineral = new javax.swing.JLabel();
        precioAguamineral = new javax.swing.JLabel();
        signoPrecio9 = new javax.swing.JLabel();
        etiTelimon = new javax.swing.JLabel();
        precioteLimon = new javax.swing.JLabel();
        signoPrecio10 = new javax.swing.JLabel();
        botonFactura = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        etipasta = new javax.swing.JLabel();
        etiTagliatelle = new javax.swing.JLabel();
        signoPrecio11 = new javax.swing.JLabel();
        precioTagliatelle = new javax.swing.JLabel();
        etiMarinara = new javax.swing.JLabel();
        signoPrecio12 = new javax.swing.JLabel();
        precioMarinara = new javax.swing.JLabel();
        etiPuttanesca = new javax.swing.JLabel();
        signoPrecio13 = new javax.swing.JLabel();
        precioPuttanesca = new javax.swing.JLabel();
        etiBolognese = new javax.swing.JLabel();
        signoPrecio14 = new javax.swing.JLabel();
        precioBolognese = new javax.swing.JLabel();
        etiAmatriciana = new javax.swing.JLabel();
        signoPrecio15 = new javax.swing.JLabel();
        precioAmatriciana = new javax.swing.JLabel();
        etiSaludo = new javax.swing.JLabel();
        etiFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bambino");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(etiPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 200, 120));

        pizzaNapolitana.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        pizzaNapolitana.setForeground(new java.awt.Color(255, 255, 255));
        pizzaNapolitana.setText("Pizza Napolitana");
        pizzaNapolitana.setToolTipText("Clic aqui para pedir");
        pizzaNapolitana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pizzaNapolitanaMouseClicked(evt);
            }
        });
        getContentPane().add(pizzaNapolitana, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 120, 20));

        precPizzaNapolitana.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precPizzaNapolitana.setForeground(new java.awt.Color(255, 255, 255));
        precPizzaNapolitana.setText("35000");
        getContentPane().add(precPizzaNapolitana, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 40, 20));

        signoPrecio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signoPrecio.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio.setText("...$");
        getContentPane().add(signoPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, 20));
        getContentPane().add(etiImangenBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 200, 120));

        pizzaMargarita.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        pizzaMargarita.setForeground(new java.awt.Color(255, 255, 255));
        pizzaMargarita.setText("Pizza Margarita");
        pizzaMargarita.setToolTipText("Clic aqui para pedir");
        pizzaMargarita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pizzaMargaritaMouseClicked(evt);
            }
        });
        getContentPane().add(pizzaMargarita, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 110, 20));

        precPizzaMargarita.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precPizzaMargarita.setForeground(new java.awt.Color(255, 255, 255));
        precPizzaMargarita.setText("37000");
        getContentPane().add(precPizzaMargarita, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 40, 20));

        signoPrecio1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signoPrecio1.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio1.setText("...$");
        getContentPane().add(signoPrecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, -1, 20));

        pizzaCapricciosa.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        pizzaCapricciosa.setForeground(new java.awt.Color(255, 255, 255));
        pizzaCapricciosa.setText("Pizza Capricciosa");
        pizzaCapricciosa.setToolTipText("Clic aqui para pedir");
        pizzaCapricciosa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pizzaCapricciosaMouseClicked(evt);
            }
        });
        getContentPane().add(pizzaCapricciosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 140, 20));

        precPizzaCapricciosa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precPizzaCapricciosa.setForeground(new java.awt.Color(255, 255, 255));
        precPizzaCapricciosa.setText("42000");
        getContentPane().add(precPizzaCapricciosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 40, 20));

        signoPrecio2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signoPrecio2.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio2.setText("...$");
        getContentPane().add(signoPrecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, -1, 20));

        pizzaFruttidimare.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        pizzaFruttidimare.setForeground(new java.awt.Color(255, 255, 255));
        pizzaFruttidimare.setText("Pizza Frutti di mare");
        pizzaFruttidimare.setToolTipText("Clic aqui para pedir");
        pizzaFruttidimare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pizzaFruttidimareMouseClicked(evt);
            }
        });
        getContentPane().add(pizzaFruttidimare, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 140, 20));

        precPizzaFruttidimare.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precPizzaFruttidimare.setForeground(new java.awt.Color(255, 255, 255));
        precPizzaFruttidimare.setText("32000");
        getContentPane().add(precPizzaFruttidimare, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 40, 20));

        signoPrecio3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signoPrecio3.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio3.setText("...$");
        getContentPane().add(signoPrecio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, -1, 20));

        pizzaBoscaiola.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        pizzaBoscaiola.setForeground(new java.awt.Color(255, 255, 255));
        pizzaBoscaiola.setText("Pizza Boscaiola");
        pizzaBoscaiola.setToolTipText("Clic aqui para pedir");
        pizzaBoscaiola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pizzaBoscaiolaMouseClicked(evt);
            }
        });
        getContentPane().add(pizzaBoscaiola, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 120, 20));

        precPizzaBoscaiola.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precPizzaBoscaiola.setForeground(new java.awt.Color(255, 255, 255));
        precPizzaBoscaiola.setText("34000");
        getContentPane().add(precPizzaBoscaiola, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 40, 20));

        signoPrecio4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signoPrecio4.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio4.setText("...$");
        getContentPane().add(signoPrecio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, -1, 20));

        etiLimonada.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiLimonada.setForeground(new java.awt.Color(255, 255, 255));
        etiLimonada.setText("Limonada");
        etiLimonada.setToolTipText("Clic aqui para pedir");
        etiLimonada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiLimonadaMouseClicked(evt);
            }
        });
        getContentPane().add(etiLimonada, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, 90, 20));

        precioLimonada.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precioLimonada.setForeground(new java.awt.Color(255, 255, 255));
        precioLimonada.setText("15000");
        getContentPane().add(precioLimonada, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 420, 40, 20));

        signoPrecio5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signoPrecio5.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio5.setText("...$");
        getContentPane().add(signoPrecio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, -1, 20));

        etiCocacola.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiCocacola.setForeground(new java.awt.Color(255, 255, 255));
        etiCocacola.setText("Coca cola");
        etiCocacola.setToolTipText("Clic aqui para pedir");
        etiCocacola.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiCocacolaMouseClicked(evt);
            }
        });
        getContentPane().add(etiCocacola, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 460, 90, 20));

        precioCocacola.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precioCocacola.setForeground(new java.awt.Color(255, 255, 255));
        precioCocacola.setText("12000");
        getContentPane().add(precioCocacola, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 460, 40, 20));

        signoPrecio6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signoPrecio6.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio6.setText("...$");
        getContentPane().add(signoPrecio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 460, -1, 20));

        etiPepsi.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiPepsi.setForeground(new java.awt.Color(255, 255, 255));
        etiPepsi.setText("Pepsi");
        etiPepsi.setToolTipText("Clic aqui para pedir");
        etiPepsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiPepsiMouseClicked(evt);
            }
        });
        getContentPane().add(etiPepsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 500, 90, 20));

        precioPepsi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precioPepsi.setForeground(new java.awt.Color(255, 255, 255));
        precioPepsi.setText("12000");
        getContentPane().add(precioPepsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 500, 40, 20));

        signoPrecio7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signoPrecio7.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio7.setText("...$");
        getContentPane().add(signoPrecio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 500, -1, 20));

        etiAgua.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiAgua.setForeground(new java.awt.Color(255, 255, 255));
        etiAgua.setText("Agua");
        etiAgua.setToolTipText("Clic aqui para pedir");
        etiAgua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiAguaMouseClicked(evt);
            }
        });
        getContentPane().add(etiAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 540, 90, 20));

        precioAgua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precioAgua.setForeground(new java.awt.Color(255, 255, 255));
        precioAgua.setText("7000");
        getContentPane().add(precioAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 540, 40, 20));

        signoPrecio8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signoPrecio8.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio8.setText("...$");
        getContentPane().add(signoPrecio8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 540, -1, 20));

        etiAguamineral.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiAguamineral.setForeground(new java.awt.Color(255, 255, 255));
        etiAguamineral.setText("Agua mineral");
        etiAguamineral.setToolTipText("Clic aqui para pedir");
        etiAguamineral.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiAguamineralMouseClicked(evt);
            }
        });
        getContentPane().add(etiAguamineral, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 580, 110, 20));

        precioAguamineral.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precioAguamineral.setForeground(new java.awt.Color(255, 255, 255));
        precioAguamineral.setText("8000");
        getContentPane().add(precioAguamineral, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 580, 40, 20));

        signoPrecio9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signoPrecio9.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio9.setText("...$");
        getContentPane().add(signoPrecio9, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 580, -1, 20));

        etiTelimon.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiTelimon.setForeground(new java.awt.Color(255, 255, 255));
        etiTelimon.setText("Te de limon");
        etiTelimon.setToolTipText("Clic aqui para pedir");
        etiTelimon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiTelimonMouseClicked(evt);
            }
        });
        getContentPane().add(etiTelimon, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 90, 20));

        precioteLimon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precioteLimon.setForeground(new java.awt.Color(255, 255, 255));
        precioteLimon.setText("12000");
        getContentPane().add(precioteLimon, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 380, 40, 20));

        signoPrecio10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signoPrecio10.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio10.setText("...$");
        getContentPane().add(signoPrecio10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, -1, 20));

        botonFactura.setBackground(new java.awt.Color(153, 255, 153));
        botonFactura.setText("Factura");
        botonFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(botonFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 640, -1, -1));

        btnVolver.setText("<<");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 640, -1, -1));
        getContentPane().add(etipasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 200, 120));

        etiTagliatelle.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiTagliatelle.setForeground(new java.awt.Color(255, 255, 255));
        etiTagliatelle.setText("Tagliatelle");
        etiTagliatelle.setToolTipText("Clic aqui para pedir");
        etiTagliatelle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiTagliatelleMouseClicked(evt);
            }
        });
        getContentPane().add(etiTagliatelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 90, -1));

        signoPrecio11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signoPrecio11.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio11.setText("...$");
        getContentPane().add(signoPrecio11, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, -1, -1));

        precioTagliatelle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precioTagliatelle.setForeground(new java.awt.Color(255, 255, 255));
        precioTagliatelle.setText("25000");
        getContentPane().add(precioTagliatelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, -1, 20));

        etiMarinara.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiMarinara.setForeground(new java.awt.Color(255, 255, 255));
        etiMarinara.setText("Marinara");
        etiMarinara.setToolTipText("Clic aqui para pedir");
        etiMarinara.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiMarinaraMouseClicked(evt);
            }
        });
        getContentPane().add(etiMarinara, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 80, -1));

        signoPrecio12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signoPrecio12.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio12.setText("...$");
        getContentPane().add(signoPrecio12, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 420, -1, 20));

        precioMarinara.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precioMarinara.setForeground(new java.awt.Color(255, 255, 255));
        precioMarinara.setText("24000");
        getContentPane().add(precioMarinara, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, -1, -1));

        etiPuttanesca.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiPuttanesca.setForeground(new java.awt.Color(255, 255, 255));
        etiPuttanesca.setText("Puttanesca");
        etiPuttanesca.setToolTipText("Clic aqui para pedir");
        etiPuttanesca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiPuttanescaMouseClicked(evt);
            }
        });
        getContentPane().add(etiPuttanesca, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 80, -1));

        signoPrecio13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signoPrecio13.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio13.setText("...$");
        getContentPane().add(signoPrecio13, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 460, -1, -1));

        precioPuttanesca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precioPuttanesca.setForeground(new java.awt.Color(255, 255, 255));
        precioPuttanesca.setText("30000");
        getContentPane().add(precioPuttanesca, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 460, 40, -1));

        etiBolognese.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiBolognese.setForeground(new java.awt.Color(255, 255, 255));
        etiBolognese.setText("Boloñesa");
        etiBolognese.setToolTipText("Clic aqui para pedir");
        etiBolognese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiBologneseMouseClicked(evt);
            }
        });
        getContentPane().add(etiBolognese, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 90, -1));

        signoPrecio14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signoPrecio14.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio14.setText("...$");
        getContentPane().add(signoPrecio14, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 500, -1, -1));

        precioBolognese.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precioBolognese.setForeground(new java.awt.Color(255, 255, 255));
        precioBolognese.setText("28000");
        getContentPane().add(precioBolognese, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, -1, -1));

        etiAmatriciana.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        etiAmatriciana.setForeground(new java.awt.Color(255, 255, 255));
        etiAmatriciana.setText("Amatriciana");
        etiAmatriciana.setToolTipText("Clic aqui para pedir");
        etiAmatriciana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                etiAmatricianaMouseClicked(evt);
            }
        });
        getContentPane().add(etiAmatriciana, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 90, -1));

        signoPrecio15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signoPrecio15.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio15.setText("...$");
        getContentPane().add(signoPrecio15, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 540, -1, -1));

        precioAmatriciana.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        precioAmatriciana.setForeground(new java.awt.Color(255, 255, 255));
        precioAmatriciana.setText("27000");
        getContentPane().add(precioAmatriciana, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, -1, -1));

        etiSaludo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        etiSaludo.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(etiSaludo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 450, 30));

        etiFondo.setBackground(new java.awt.Color(51, 51, 51));
        etiFondo.setToolTipText("Click en un plato para ordenar");
        getContentPane().add(etiFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFacturaActionPerformed
        float totalGeneral = VentanaPrincipal.gestionVenta.calcularTotalGeneral();
        
        double iva = 0.10;
        
        double propina = totalGeneral * iva;
        
        double totalPagar = totalGeneral + propina;
        
        
        
                
        
        
        JOptionPane.showMessageDialog(this, """
                                            RESUMEN DE LA ORDEN \n
                                            Por la utilizacion de nuestro servicio se le adicionara el 10 % a la factura: \n
                                            Total por los platos seleccionados: $""" + totalGeneral + "\n" +
                                            "Valor por el servicio:  $" + propina + "\n" +
                                            "El total a pagar por los platos seleccionados y el servicio es:  $" + totalPagar + "\n" + "\n" + 
                                            "MUCHAS GRACIAS POR UTILIZAR NUESTRO SERVICIO Y PREFERIR BAMBINO"  );
 
    }//GEN-LAST:event_botonFacturaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal ventana =new VentanaPrincipal();
        ventana.setVisible(true);
        
        this.dispose();
            
    }//GEN-LAST:event_btnVolverActionPerformed

    
    private void pizzaNapolitanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pizzaNapolitanaMouseClicked
        // TODO add your handling code here:
        Producto producto = new Producto();
        producto.ingredientes= new String[3];
        producto.nombre=pizzaNapolitana.getText();
        producto.precio=Float.parseFloat(precPizzaNapolitana.getText());
        
        producto.ingredientes[0]="Ajo";
        producto.ingredientes[1]="Perejil";
        producto.ingredientes[2]="Hierbas";
        
        
        VentanaVentaComida vistaplato = new VentanaVentaComida(producto);
        
        vistaplato.setLocationRelativeTo(this);
        vistaplato.setVisible(true);
        
       
    }//GEN-LAST:event_pizzaNapolitanaMouseClicked

    private void pizzaMargaritaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pizzaMargaritaMouseClicked
        // TODO add your handling code here:
        Producto producto = new Producto();
        producto.ingredientes= new String[3];
        producto.nombre=pizzaMargarita.getText();
        producto.precio=Float.parseFloat(precPizzaMargarita.getText());
        
        producto.ingredientes[0]="Ají";
        producto.ingredientes[1]="Tomate";
        producto.ingredientes[2]="Oregano";
        
        
           VentanaVentaComida vistaplato = new VentanaVentaComida(producto);
        
        vistaplato.setLocationRelativeTo(this);
        vistaplato.setVisible(true);
    }//GEN-LAST:event_pizzaMargaritaMouseClicked

    private void pizzaCapricciosaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pizzaCapricciosaMouseClicked
        Producto producto = new Producto();
        producto.ingredientes= new String[3];
        producto.nombre=pizzaCapricciosa.getText();
        producto.precio=Float.parseFloat(precPizzaCapricciosa.getText());
        
        producto.ingredientes[0]="Albahaca";
        producto.ingredientes[1]="Alcachofa";
        producto.ingredientes[2]="Champiñones";
        
        
         VentanaVentaComida vistaplato = new VentanaVentaComida(producto);
        
        vistaplato.setLocationRelativeTo(this);
        vistaplato.setVisible(true);
        
    }//GEN-LAST:event_pizzaCapricciosaMouseClicked

    private void pizzaFruttidimareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pizzaFruttidimareMouseClicked
        // TODO add your handling code here:
        Producto producto = new Producto();
        producto.ingredientes= new String[3];
        producto.nombre=pizzaFruttidimare.getText();
        producto.precio=Float.parseFloat(precPizzaFruttidimare.getText());
        
        producto.ingredientes[0]="jamon";
        producto.ingredientes[1]="pepperoni";
        producto.ingredientes[2]="champiñones";
        
        
         VentanaVentaComida vistaplato = new VentanaVentaComida(producto);
        
        vistaplato.setLocationRelativeTo(this);
        vistaplato.setVisible(true);
        
    }//GEN-LAST:event_pizzaFruttidimareMouseClicked

    private void pizzaBoscaiolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pizzaBoscaiolaMouseClicked
        Producto producto = new Producto();
        producto.ingredientes= new String[3];
        producto.nombre=pizzaBoscaiola.getText();
        producto.precio=Float.parseFloat(precPizzaBoscaiola.getText());
        
        producto.ingredientes[0]="pimientos";
        producto.ingredientes[1]="perejil";
        producto.ingredientes[2]="champiñones";
        
        
         VentanaVentaComida vistaplato = new VentanaVentaComida(producto);
        
        vistaplato.setLocationRelativeTo(this);
        vistaplato.setVisible(true);
    }//GEN-LAST:event_pizzaBoscaiolaMouseClicked

    private void etiTelimonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiTelimonMouseClicked
        // TODO add your handling code here:
        Producto producto = new Producto();
        producto.nombre=etiTelimon.getText();
        producto.precio=Float.parseFloat(precioteLimon.getText());
        
        
         VentanaVentaBebida vistaplato = new VentanaVentaBebida(producto);
        
        vistaplato.setLocationRelativeTo(this);
        vistaplato.setVisible(true);
    }//GEN-LAST:event_etiTelimonMouseClicked

    private void etiLimonadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiLimonadaMouseClicked
        // TODO add your handling code here:
        Producto producto = new Producto();
        producto.nombre=etiLimonada.getText();
        producto.precio=Float.parseFloat(precioLimonada.getText());
         VentanaVentaBebida vistaplato = new VentanaVentaBebida(producto);
        
        vistaplato.setLocationRelativeTo(this);
        vistaplato.setVisible(true);
    }//GEN-LAST:event_etiLimonadaMouseClicked

    private void etiCocacolaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiCocacolaMouseClicked
        // TODO add your handling code here:
        Producto producto = new Producto();
        producto.nombre=etiCocacola.getText();
        producto.precio=Float.parseFloat(precioCocacola.getText());
         VentanaVentaBebida vistaplato = new VentanaVentaBebida(producto);
        
        vistaplato.setLocationRelativeTo(this);
        vistaplato.setVisible(true);
    }//GEN-LAST:event_etiCocacolaMouseClicked

    private void etiPepsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiPepsiMouseClicked
        // TODO add your handling code here:
        Producto producto = new Producto();
        producto.nombre=etiPepsi.getText();
        producto.precio=Float.parseFloat(precioPepsi.getText());
         VentanaVentaBebida vistaplato = new VentanaVentaBebida(producto);
        
        vistaplato.setLocationRelativeTo(this);
        vistaplato.setVisible(true);
    }//GEN-LAST:event_etiPepsiMouseClicked

    private void etiAguaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiAguaMouseClicked
        // TODO add your handling code here:
        Producto producto = new Producto();
        producto.nombre=etiAgua.getText();
        producto.precio=Float.parseFloat(precioAgua.getText());
         VentanaVentaBebida vistaplato = new VentanaVentaBebida(producto);
        
        vistaplato.setLocationRelativeTo(this);
        vistaplato.setVisible(true);
    }//GEN-LAST:event_etiAguaMouseClicked

    private void etiAguamineralMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiAguamineralMouseClicked
        // TODO add your handling code here:
        Producto producto = new Producto();
        producto.nombre=etiAguamineral.getText();
        producto.precio=Float.parseFloat(precioAguamineral.getText());
         VentanaVentaBebida vistaplato = new VentanaVentaBebida(producto);
        
        vistaplato.setLocationRelativeTo(this);
        vistaplato.setVisible(true);
    }//GEN-LAST:event_etiAguamineralMouseClicked

    private void etiTagliatelleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiTagliatelleMouseClicked
        // TODO add your handling code here:
        Producto producto = new Producto();
        producto.ingredientes= new String[3];
        producto.nombre=etiTagliatelle.getText();
        producto.precio=Float.parseFloat(precioTagliatelle.getText());
        
        producto.ingredientes[0]="Queso Parmesano";
        producto.ingredientes[1]="Salsa cremosa";
        
        
        
         VentanaVentaComida vistaplato = new VentanaVentaComida(producto);
        
        vistaplato.setLocationRelativeTo(this);
        vistaplato.setVisible(true);
    }//GEN-LAST:event_etiTagliatelleMouseClicked

    private void etiMarinaraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiMarinaraMouseClicked
        // TODO add your handling code here:
        Producto producto = new Producto();
        producto.ingredientes= new String[3];
        producto.nombre=etiMarinara.getText();
        producto.precio=Float.parseFloat(precioMarinara.getText());
        
        producto.ingredientes[0]="Calamar";
        producto.ingredientes[1]="Mejillones";
        producto.ingredientes[2]="Langostinos";
        
        
         VentanaVentaComida vistaplato = new VentanaVentaComida(producto);
        
        vistaplato.setLocationRelativeTo(this);
        vistaplato.setVisible(true);
    }//GEN-LAST:event_etiMarinaraMouseClicked

    private void etiPuttanescaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiPuttanescaMouseClicked
        // TODO add your handling code here:
        Producto producto = new Producto();
        producto.ingredientes= new String[3];
        producto.nombre=etiPuttanesca.getText();
        producto.precio=Float.parseFloat(precioPuttanesca.getText());
        
        producto.ingredientes[0]="Aceituna negra";
        producto.ingredientes[1]="Guindilla";
        
        
         VentanaVentaComida vistaplato = new VentanaVentaComida(producto);
        
        vistaplato.setLocationRelativeTo(this);
        vistaplato.setVisible(true);
    }//GEN-LAST:event_etiPuttanescaMouseClicked

    private void etiBologneseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiBologneseMouseClicked
        // TODO add your handling code here:
        Producto producto = new Producto();
        producto.ingredientes= new String[3];
        producto.nombre=etiBolognese.getText();
        producto.precio=Float.parseFloat(precioBolognese.getText());
        
        producto.ingredientes[0]="Albahaca";
        producto.ingredientes[1]="Queso parmesano";
        
        
         VentanaVentaComida vistaplato = new VentanaVentaComida(producto);
        
        vistaplato.setLocationRelativeTo(this);
        vistaplato.setVisible(true);
    }//GEN-LAST:event_etiBologneseMouseClicked

    private void etiAmatricianaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiAmatricianaMouseClicked
        // TODO add your handling code here:
        Producto producto = new Producto();
        producto.ingredientes= new String[3];
        producto.nombre=etiAmatriciana.getText();
        producto.precio=Float.parseFloat(precioAmatriciana.getText());
        
        producto.ingredientes[0]="Papada de cerdo (guanciale)";
        producto.ingredientes[1]="Queso pecorino";
        
        
         VentanaVentaComida vistaplato = new VentanaVentaComida(producto);
        
        vistaplato.setLocationRelativeTo(this);
        vistaplato.setVisible(true);
    }//GEN-LAST:event_etiAmatricianaMouseClicked
    
    public void SetImageLabel(JLabel nombrelabel, String root){
        ImageIcon imagen = new ImageIcon(root); 
        Icon icon = new ImageIcon(
                imagen.getImage().getScaledInstance(nombrelabel.getWidth(), nombrelabel.getHeight(), Image.SCALE_DEFAULT));
        nombrelabel.setIcon(icon);
        this.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonFactura;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel etiAgua;
    private javax.swing.JLabel etiAguamineral;
    private javax.swing.JLabel etiAmatriciana;
    private javax.swing.JLabel etiBolognese;
    private javax.swing.JLabel etiCocacola;
    private javax.swing.JLabel etiFondo;
    private javax.swing.JLabel etiImangenBebidas;
    private javax.swing.JLabel etiLimonada;
    private javax.swing.JLabel etiMarinara;
    private javax.swing.JLabel etiPepsi;
    private javax.swing.JLabel etiPizza;
    private javax.swing.JLabel etiPuttanesca;
    private javax.swing.JLabel etiSaludo;
    private javax.swing.JLabel etiTagliatelle;
    private javax.swing.JLabel etiTelimon;
    private javax.swing.JLabel etipasta;
    private javax.swing.JLabel pizzaBoscaiola;
    private javax.swing.JLabel pizzaCapricciosa;
    private javax.swing.JLabel pizzaFruttidimare;
    private javax.swing.JLabel pizzaMargarita;
    private javax.swing.JLabel pizzaNapolitana;
    private javax.swing.JLabel precPizzaBoscaiola;
    private javax.swing.JLabel precPizzaCapricciosa;
    private javax.swing.JLabel precPizzaFruttidimare;
    private javax.swing.JLabel precPizzaMargarita;
    private javax.swing.JLabel precPizzaNapolitana;
    private javax.swing.JLabel precioAgua;
    private javax.swing.JLabel precioAguamineral;
    private javax.swing.JLabel precioAmatriciana;
    private javax.swing.JLabel precioBolognese;
    private javax.swing.JLabel precioCocacola;
    private javax.swing.JLabel precioLimonada;
    private javax.swing.JLabel precioMarinara;
    private javax.swing.JLabel precioPepsi;
    private javax.swing.JLabel precioPuttanesca;
    private javax.swing.JLabel precioTagliatelle;
    private javax.swing.JLabel precioteLimon;
    private javax.swing.JLabel signoPrecio;
    private javax.swing.JLabel signoPrecio1;
    private javax.swing.JLabel signoPrecio10;
    private javax.swing.JLabel signoPrecio11;
    private javax.swing.JLabel signoPrecio12;
    private javax.swing.JLabel signoPrecio13;
    private javax.swing.JLabel signoPrecio14;
    private javax.swing.JLabel signoPrecio15;
    private javax.swing.JLabel signoPrecio2;
    private javax.swing.JLabel signoPrecio3;
    private javax.swing.JLabel signoPrecio4;
    private javax.swing.JLabel signoPrecio5;
    private javax.swing.JLabel signoPrecio6;
    private javax.swing.JLabel signoPrecio7;
    private javax.swing.JLabel signoPrecio8;
    private javax.swing.JLabel signoPrecio9;
    // End of variables declaration//GEN-END:variables


    
}
