package co.edu.unicolombo.pb.proaula.views;

import co.edu.unicolombo.pb.proaula.conceptos.Cliente;
import co.edu.unicolombo.pb.proaula.crud.GestionVentas;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class VentanaRegistro extends javax.swing.JFrame {

    public static GestionVentas gestionVenta;

    public VentanaRegistro() {

        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        int x = (int) ((screenSize.getWidth() - this.getWidth()) / 2);
        int y = (int) ((screenSize.getHeight() - this.getHeight()) / 2);

        this.setLocation(x, y);
        btnSiguiente.setEnabled(false);
        gestionVenta = new GestionVentas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        etiTitulo = new javax.swing.JLabel();
        etiDocumento = new javax.swing.JLabel();
        usuarioText = new javax.swing.JTextField();
        btnSiguiente = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        etiUsuario = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        documentoText = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        etiImagen = new javax.swing.JLabel();
        etiSalir = new javax.swing.JLabel();
        etiIniciarSesion = new javax.swing.JLabel();
        etiRegistrarse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bambino");
        setPreferredSize(new java.awt.Dimension(780, 500));
        setResizable(false);

        fondo.setBackground(new java.awt.Color(255, 255, 255));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiTitulo.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        etiTitulo.setForeground(new java.awt.Color(51, 51, 51));
        etiTitulo.setText("Registro");
        etiTitulo.setAlignmentX(0.5F);
        fondo.add(etiTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 120, -1));

        etiDocumento.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        etiDocumento.setForeground(new java.awt.Color(51, 51, 51));
        etiDocumento.setText("DOCUMENTO");
        fondo.add(etiDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 140, 24));

        usuarioText.setBackground(new java.awt.Color(255, 255, 255));
        usuarioText.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        usuarioText.setForeground(new java.awt.Color(102, 102, 102));
        usuarioText.setText("Ingrese su nombre de usuario");
        usuarioText.setBorder(null);
        usuarioText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioTextActionPerformed(evt);
            }
        });
        fondo.add(usuarioText, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 370, 30));

        btnSiguiente.setBackground(new java.awt.Color(153, 255, 153));
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });
        fondo.add(btnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 350, -1, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        fondo.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, -1));
        fondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 370, -1));

        etiUsuario.setFont(new java.awt.Font("Roboto Light", 1, 12)); // NOI18N
        etiUsuario.setForeground(new java.awt.Color(51, 51, 51));
        etiUsuario.setText("USUARIO");
        fondo.add(etiUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 140, 24));
        fondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 370, -1));

        documentoText.setBackground(new java.awt.Color(255, 255, 255));
        documentoText.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        documentoText.setForeground(new java.awt.Color(102, 102, 102));
        documentoText.setText("Ingrese su número de documento");
        documentoText.setBorder(null);
        documentoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentoTextActionPerformed(evt);
            }
        });
        fondo.add(documentoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, 370, 30));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiImagen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-male-user-100.png"))); // NOI18N
        jPanel1.add(etiImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 280, 100));

        etiSalir.setBackground(new java.awt.Color(0, 153, 204));
        etiSalir.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        etiSalir.setForeground(new java.awt.Color(255, 255, 255));
        etiSalir.setHorizontalAlignment(10
        );
        etiSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-salida-50.png"))); // NOI18N
        etiSalir.setText(" Salir");
        etiSalir.setOpaque(true);
        etiSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiSalirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiSalirMouseExited(evt);
            }
        });
        jPanel1.add(etiSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 280, 60));

        etiIniciarSesion.setBackground(new java.awt.Color(0, 153, 204));
        etiIniciarSesion.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        etiIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        etiIniciarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-accede-redondeado-derecho-50.png"))); // NOI18N
        etiIniciarSesion.setText(" Iniciar sesión");
        etiIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        etiIniciarSesion.setOpaque(true);
        etiIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiIniciarSesionMouseExited(evt);
            }
        });
        jPanel1.add(etiIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 280, 60));

        etiRegistrarse.setBackground(new java.awt.Color(0, 153, 204));
        etiRegistrarse.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        etiRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        etiRegistrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-registro-50.png"))); // NOI18N
        etiRegistrarse.setText(" Registrarse");
        etiRegistrarse.setOpaque(true);
        etiRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                etiRegistrarseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                etiRegistrarseMouseExited(evt);
            }
        });
        jPanel1.add(etiRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 280, 60));

        fondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        Cliente cliente = new Cliente();
        cliente.nombre = usuarioText.getText();
        cliente.documento = usuarioText.getText();
        if (cliente.nombre.isEmpty() || !validarCaracteres(cliente.nombre) || cliente.nombre.charAt(0) == ' ') {
            JOptionPane.showMessageDialog(null, "Nombre invalido.");
            return;
        }

        if (!validarNumeros(cliente.documento) || cliente.documento.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Número de documento invalido.");
            return;
        }
        
        gestionVenta.setCliente(cliente);
        
        btnSiguiente.setEnabled(true);
        try {
            BufferedWriter writer = new BufferedWriter(new FileWriter("Datos.txt", true));
            writer.write("DATOS CLIENTE");
            writer.newLine();
            writer.write("\nNombre: " + cliente.nombre + "\nDocumento: " + cliente.documento + "\n");
            writer.write("");
            writer.newLine();

            writer.close();
        } catch (IOException e) {
            System.err.println("Error al escribir en el archivo.");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        
        
        VentanaMenu menu = new VentanaMenu();
        //menu.setTitle("SALUDOS " + VentanaPrincipal.gestionVenta.getVenta().cliente.nombre); 
        menu.setLocationRelativeTo(null);
        menu.setVisible(true);
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, "Para seleccionar un plato presione su nombre");
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void usuarioTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioTextActionPerformed
        // TODO add your handling code here:
        btnGuardar.doClick();
    }//GEN-LAST:event_usuarioTextActionPerformed

    private void documentoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_documentoTextActionPerformed

    private void etiSalirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiSalirMouseEntered
        etiSalir.setBackground(new Color(58,167,203));
    }//GEN-LAST:event_etiSalirMouseEntered

    private void etiSalirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiSalirMouseExited
        etiSalir.setBackground(new Color(0,153,204));
    }//GEN-LAST:event_etiSalirMouseExited

    private void etiIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiIniciarSesionMouseEntered
        etiIniciarSesion.setBackground(new Color(58,167,203));
    }//GEN-LAST:event_etiIniciarSesionMouseEntered

    private void etiIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiIniciarSesionMouseExited
        etiIniciarSesion.setBackground(new Color(0,153,204));
    }//GEN-LAST:event_etiIniciarSesionMouseExited

    private void etiRegistrarseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiRegistrarseMouseEntered
        etiRegistrarse.setBackground(new Color(58,167,203));
    }//GEN-LAST:event_etiRegistrarseMouseEntered

    private void etiRegistrarseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_etiRegistrarseMouseExited
        etiRegistrarse.setBackground(new Color(0,153,204));
    }//GEN-LAST:event_etiRegistrarseMouseExited

    public void SetImageLabel(JLabel nombrelabel, String root) {
        ImageIcon imagen = new ImageIcon(root);
        Icon icon = new ImageIcon(
                imagen.getImage().getScaledInstance(nombrelabel.getWidth(), nombrelabel.getHeight(), Image.SCALE_DEFAULT));
        nombrelabel.setIcon(icon);
        this.repaint();
    }

    public static boolean validarCaracteres(String datos) {
        return datos.matches("[a-z A-Z]*");
    }

    public static boolean validarNumeros(String datos) {
        return datos.matches("[0-9]*");
    }

// Agrega un ComponentListener a tu JFrame para detectar cambios de tamaño
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JTextField documentoText;
    private javax.swing.JLabel etiDocumento;
    private javax.swing.JLabel etiImagen;
    private javax.swing.JLabel etiIniciarSesion;
    private javax.swing.JLabel etiRegistrarse;
    private javax.swing.JLabel etiSalir;
    private javax.swing.JLabel etiTitulo;
    private javax.swing.JLabel etiUsuario;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField usuarioText;
    // End of variables declaration//GEN-END:variables
}
