
package co.edu.unicolombo.pb.proaula.views;

import co.edu.unicolombo.pb.proaula.conceptos.Producto;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author alvar
 */
public final class VentanaMenu extends javax.swing.JFrame {

    /**
     * Creates new form MenuRestaurante
     */
    
    public VentanaMenu() {
        
        initComponents();
         SetImageLabel(etiPizza,"src/imagenes/pizza.jpeg");
         SetImageLabel(etiImangenBebidas,"src/imagenes/Limonada.jpg");
          SetImageLabel(etiFondo,"src/imagenes/menu2.jpg");
           
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

            int x = (int) ((screenSize.getWidth() - this.getWidth()) / 2);
            int y = (int) ((screenSize.getHeight() - this.getHeight()) / 2);

            this.setLocation(x, y);
         
            
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiPizza = new javax.swing.JLabel();
        pizzaNapolitana = new javax.swing.JLabel();
        precPizzaNapolitana = new javax.swing.JLabel();
        signoPrecio = new javax.swing.JLabel();
        etiImangenBebidas = new javax.swing.JLabel();
        pizzaMargarita = new javax.swing.JLabel();
        precPizzaMargarita = new javax.swing.JLabel();
        signoPrecio1 = new javax.swing.JLabel();
        pizzaCapricciosa = new javax.swing.JLabel();
        precPizzaCapricciosa = new javax.swing.JLabel();
        signoPrecio2 = new javax.swing.JLabel();
        PizzaFruttidimare = new javax.swing.JLabel();
        precPizzaFruttidimare = new javax.swing.JLabel();
        signoPrecio3 = new javax.swing.JLabel();
        PizzaBoscaiola = new javax.swing.JLabel();
        precPizzaBoscaiola = new javax.swing.JLabel();
        signoPrecio4 = new javax.swing.JLabel();
        etiLimonada = new javax.swing.JLabel();
        precioLimonada = new javax.swing.JLabel();
        signoPrecio5 = new javax.swing.JLabel();
        etiCocala = new javax.swing.JLabel();
        precioCocacola = new javax.swing.JLabel();
        signoPrecio6 = new javax.swing.JLabel();
        etiPepsi = new javax.swing.JLabel();
        precioPepsi = new javax.swing.JLabel();
        signoPrecio7 = new javax.swing.JLabel();
        etiAgua = new javax.swing.JLabel();
        precioAgua = new javax.swing.JLabel();
        signoPrecio8 = new javax.swing.JLabel();
        etiAguamineral = new javax.swing.JLabel();
        precioAguamineral = new javax.swing.JLabel();
        signoPrecio9 = new javax.swing.JLabel();
        etiTelimon = new javax.swing.JLabel();
        precioteLimon = new javax.swing.JLabel();
        signoPrecio10 = new javax.swing.JLabel();
        botonFactura = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        etiFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(etiPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 200, 120));

        pizzaNapolitana.setForeground(new java.awt.Color(255, 255, 255));
        pizzaNapolitana.setText("Pizza napolitana");
        pizzaNapolitana.setToolTipText("Clic aqui para configurar");
        pizzaNapolitana.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pizzaNapolitanaMouseClicked(evt);
            }
        });
        getContentPane().add(pizzaNapolitana, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 110, 20));

        precPizzaNapolitana.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        precPizzaNapolitana.setForeground(new java.awt.Color(255, 255, 255));
        precPizzaNapolitana.setText("35000");
        getContentPane().add(precPizzaNapolitana, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 40, 20));

        signoPrecio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signoPrecio.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio.setText("...$");
        getContentPane().add(signoPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, -1, 20));
        getContentPane().add(etiImangenBebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 200, 120));

        pizzaMargarita.setForeground(new java.awt.Color(255, 255, 255));
        pizzaMargarita.setText("Pizza margarita");
        pizzaMargarita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pizzaMargaritaMouseClicked(evt);
            }
        });
        getContentPane().add(pizzaMargarita, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 110, 20));

        precPizzaMargarita.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        precPizzaMargarita.setForeground(new java.awt.Color(255, 255, 255));
        precPizzaMargarita.setText("37000");
        getContentPane().add(precPizzaMargarita, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 40, 20));

        signoPrecio1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signoPrecio1.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio1.setText("...$");
        getContentPane().add(signoPrecio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, -1, 20));

        pizzaCapricciosa.setForeground(new java.awt.Color(255, 255, 255));
        pizzaCapricciosa.setText("Pizza capricciosa");
        pizzaCapricciosa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pizzaCapricciosaMouseClicked(evt);
            }
        });
        getContentPane().add(pizzaCapricciosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 110, 20));

        precPizzaCapricciosa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        precPizzaCapricciosa.setForeground(new java.awt.Color(255, 255, 255));
        precPizzaCapricciosa.setText("42000");
        getContentPane().add(precPizzaCapricciosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 40, 20));

        signoPrecio2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signoPrecio2.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio2.setText("...$");
        getContentPane().add(signoPrecio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 440, -1, 20));

        PizzaFruttidimare.setForeground(new java.awt.Color(255, 255, 255));
        PizzaFruttidimare.setText("Pizza frutti di mare");
        getContentPane().add(PizzaFruttidimare, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 110, 20));

        precPizzaFruttidimare.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        precPizzaFruttidimare.setForeground(new java.awt.Color(255, 255, 255));
        precPizzaFruttidimare.setText("32000");
        getContentPane().add(precPizzaFruttidimare, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 40, 20));

        signoPrecio3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signoPrecio3.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio3.setText("...$");
        getContentPane().add(signoPrecio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, -1, 20));

        PizzaBoscaiola.setForeground(new java.awt.Color(255, 255, 255));
        PizzaBoscaiola.setText("Pizza boscaiola");
        getContentPane().add(PizzaBoscaiola, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 100, 20));

        precPizzaBoscaiola.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        precPizzaBoscaiola.setForeground(new java.awt.Color(255, 255, 255));
        precPizzaBoscaiola.setText("34000");
        getContentPane().add(precPizzaBoscaiola, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 520, 40, 20));

        signoPrecio4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signoPrecio4.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio4.setText("...$");
        getContentPane().add(signoPrecio4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, -1, 20));

        etiLimonada.setForeground(new java.awt.Color(255, 255, 255));
        etiLimonada.setText("Limonada");
        getContentPane().add(etiLimonada, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 90, 20));

        precioLimonada.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        precioLimonada.setForeground(new java.awt.Color(255, 255, 255));
        precioLimonada.setText("15000");
        getContentPane().add(precioLimonada, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 40, 20));

        signoPrecio5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signoPrecio5.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio5.setText("...$");
        getContentPane().add(signoPrecio5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, -1, 20));

        etiCocala.setForeground(new java.awt.Color(255, 255, 255));
        etiCocala.setText("Coca cola");
        getContentPane().add(etiCocala, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 440, 90, 20));

        precioCocacola.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        precioCocacola.setForeground(new java.awt.Color(255, 255, 255));
        precioCocacola.setText("12000");
        getContentPane().add(precioCocacola, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 40, 20));

        signoPrecio6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signoPrecio6.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio6.setText("...$");
        getContentPane().add(signoPrecio6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, -1, 20));

        etiPepsi.setForeground(new java.awt.Color(255, 255, 255));
        etiPepsi.setText("Pepsi");
        getContentPane().add(etiPepsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 480, 90, 20));

        precioPepsi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        precioPepsi.setForeground(new java.awt.Color(255, 255, 255));
        precioPepsi.setText("12000");
        getContentPane().add(precioPepsi, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 40, 20));

        signoPrecio7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signoPrecio7.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio7.setText("...$");
        getContentPane().add(signoPrecio7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 480, -1, 20));

        etiAgua.setForeground(new java.awt.Color(255, 255, 255));
        etiAgua.setText("Agua");
        getContentPane().add(etiAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 520, 90, 20));

        precioAgua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        precioAgua.setForeground(new java.awt.Color(255, 255, 255));
        precioAgua.setText("7000");
        getContentPane().add(precioAgua, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 520, 40, 20));

        signoPrecio8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signoPrecio8.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio8.setText("...$");
        getContentPane().add(signoPrecio8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 520, -1, 20));

        etiAguamineral.setForeground(new java.awt.Color(255, 255, 255));
        etiAguamineral.setText("Agua mineral");
        getContentPane().add(etiAguamineral, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 560, 90, 20));

        precioAguamineral.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        precioAguamineral.setForeground(new java.awt.Color(255, 255, 255));
        precioAguamineral.setText("8000");
        getContentPane().add(precioAguamineral, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 560, 40, 20));

        signoPrecio9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signoPrecio9.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio9.setText("...$");
        getContentPane().add(signoPrecio9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 560, -1, 20));

        etiTelimon.setForeground(new java.awt.Color(255, 255, 255));
        etiTelimon.setText("Te de limon");
        getContentPane().add(etiTelimon, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 90, 20));

        precioteLimon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        precioteLimon.setForeground(new java.awt.Color(255, 255, 255));
        precioteLimon.setText("12000");
        getContentPane().add(precioteLimon, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 40, 20));

        signoPrecio10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        signoPrecio10.setForeground(new java.awt.Color(255, 255, 255));
        signoPrecio10.setText("...$");
        getContentPane().add(signoPrecio10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, -1, 20));

        botonFactura.setBackground(new java.awt.Color(153, 255, 153));
        botonFactura.setText("Factura");
        botonFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(botonFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, -1, -1));

        btnVolver.setText("<<");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 640, -1, -1));

        etiFondo.setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().add(etiFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFacturaActionPerformed
        float totalGeneral = VentanaPrincipal.gestionVenta.calcularTotalGeneral();
        JOptionPane.showConfirmDialog(this, "TOTAL FACTURA: $"+totalGeneral);

    }//GEN-LAST:event_botonFacturaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal ventana =new VentanaPrincipal();
        ventana.setVisible(true);
        this.dispose();
            
    }//GEN-LAST:event_btnVolverActionPerformed

    
    private void pizzaNapolitanaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pizzaNapolitanaMouseClicked
        // TODO add your handling code here:
        Producto producto = new Producto();
        producto.ingredientes= new String[3];
        producto.nombre=pizzaNapolitana.getText();
        producto.precio=Float.parseFloat(precPizzaNapolitana.getText());
        
        producto.ingredientes[0]="Ajo";
        producto.ingredientes[1]="Perejil";
        producto.ingredientes[2]="Hierbas";
        
        
        VentanaVentaComida vistaplato = new VentanaVentaComida(producto);
        
        vistaplato.setLocationRelativeTo(this);
        vistaplato.setVisible(true);
        
       
    }//GEN-LAST:event_pizzaNapolitanaMouseClicked

    private void pizzaMargaritaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pizzaMargaritaMouseClicked
        // TODO add your handling code here:
        Producto producto = new Producto();
        producto.ingredientes= new String[3];
        producto.nombre=pizzaMargarita.getText();
        producto.precio=Float.parseFloat(precPizzaMargarita.getText());
        
        producto.ingredientes[0]="Ají";
        producto.ingredientes[1]="Tomate";
        producto.ingredientes[2]="Oregano";
        
        
           VentanaVentaComida vistaplato = new VentanaVentaComida(producto);
        
        vistaplato.setLocationRelativeTo(this);
        vistaplato.setVisible(true);
    }//GEN-LAST:event_pizzaMargaritaMouseClicked

    private void pizzaCapricciosaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pizzaCapricciosaMouseClicked
        Producto producto = new Producto();
        producto.ingredientes= new String[3];
        producto.nombre=pizzaCapricciosa.getText();
        producto.precio=Float.parseFloat(precPizzaCapricciosa.getText());
        
        producto.ingredientes[0]="Albahaca";
        producto.ingredientes[1]="Alcachofa";
        producto.ingredientes[2]="Champiñones";
        
        
         VentanaVentaComida vistaplato = new VentanaVentaComida(producto);
        
        vistaplato.setLocationRelativeTo(this);
        vistaplato.setVisible(true);
        
    }//GEN-LAST:event_pizzaCapricciosaMouseClicked
    
    
 
    public void SetImageLabel(JLabel nombrelabel, String root){
        ImageIcon imagen = new ImageIcon(root); 
        Icon icon = new ImageIcon(
                imagen.getImage().getScaledInstance(nombrelabel.getWidth(), nombrelabel.getHeight(), Image.SCALE_DEFAULT));
        nombrelabel.setIcon(icon);
        this.repaint();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PizzaBoscaiola;
    private javax.swing.JLabel PizzaFruttidimare;
    private javax.swing.JButton botonFactura;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel etiAgua;
    private javax.swing.JLabel etiAguamineral;
    private javax.swing.JLabel etiCocala;
    private javax.swing.JLabel etiFondo;
    private javax.swing.JLabel etiImangenBebidas;
    private javax.swing.JLabel etiLimonada;
    private javax.swing.JLabel etiPepsi;
    private javax.swing.JLabel etiPizza;
    private javax.swing.JLabel etiTelimon;
    private javax.swing.JLabel pizzaCapricciosa;
    private javax.swing.JLabel pizzaMargarita;
    private javax.swing.JLabel pizzaNapolitana;
    private javax.swing.JLabel precPizzaBoscaiola;
    private javax.swing.JLabel precPizzaCapricciosa;
    private javax.swing.JLabel precPizzaFruttidimare;
    private javax.swing.JLabel precPizzaMargarita;
    private javax.swing.JLabel precPizzaNapolitana;
    private javax.swing.JLabel precioAgua;
    private javax.swing.JLabel precioAguamineral;
    private javax.swing.JLabel precioCocacola;
    private javax.swing.JLabel precioLimonada;
    private javax.swing.JLabel precioPepsi;
    private javax.swing.JLabel precioteLimon;
    private javax.swing.JLabel signoPrecio;
    private javax.swing.JLabel signoPrecio1;
    private javax.swing.JLabel signoPrecio10;
    private javax.swing.JLabel signoPrecio2;
    private javax.swing.JLabel signoPrecio3;
    private javax.swing.JLabel signoPrecio4;
    private javax.swing.JLabel signoPrecio5;
    private javax.swing.JLabel signoPrecio6;
    private javax.swing.JLabel signoPrecio7;
    private javax.swing.JLabel signoPrecio8;
    private javax.swing.JLabel signoPrecio9;
    // End of variables declaration//GEN-END:variables


    
}
